### PR TITLE
Restructure project

### PR DESCRIPTION
**Pull request by thegeman**
Many changes to the Graphalytics build system. Explaining how it works is best done by example, so to build Graphalytics with Neo4j:

1. Clone both the `graphalytics` project (to `${graphalytics}`) and the `graphalytics-platforms-neo4j` project (to `${neo4j}`).
2. Run `mvn install` in `${graphalytics}`.
3. Run `mvn package` in `${neo4j}`.
4. Run `./package-benchmark.sh neo4j 0.2-SNAPSHOT ${neo4j}` in `${graphalytics}`. Note that the arguments to this script are "platform-name", "platform-version", and "path-to-platform-repository".
5. A distribution with configuration files, scripts, and binaries for Graphalytics with Neo4j support is now created in `${graphalytics}`.

@tudelft-atlarge/graphalytics-developers, any thoughts, suggestions, etc.?

### CODE REVIEW

**Comment by thegeman** [comment]
For some reason Jenkins did not find a JDK. Retesting to see if it was a glitch or a real issue.

Jenkins, retest this please.

**Comment by mihaic** [comment]
retest this please

**Comment by mihaic** [comment]
I emailed the Jenkins admin. I will trigger another test when Jenkins is fixed.

**Comment by mihaic** [comment]
retest this please

**Comment by mihaic** [comment]
retest this please

**Comment by mihaic** [comment]
retest this please

**Comment by mihaic** [comment]
retest this please

**Comment by mihaic** [comment]
retest this please

**Pull request merged**
